# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(blank=True)),
                ('vegeterian', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VEG', (('Onion', 'Onion'),)), ('NON-VEG', (('Barbeque Chicken', 'Barbeque Chicken'),))], max_length=50, unique=True)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='ordersite.Topping'),
        ),
    ]
