# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-22 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0002_auto_20170122_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
