# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0006_auto_20170123_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='ordersite.Topping'),
        ),
    ]
