# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0007_auto_20170124_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='vegeterian',
            new_name='vegetarian',
        ),
        migrations.AddField(
            model_name='topping',
            name='vegetarian',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(choices=[('VEG', ('Black Olives', 'Paneer', 'Mushroom', 'Capsicum', 'Golden Corn', 'Jalapeno', 'Fresh Tomato', 'Red Pepper')), ('NON-VEG', ('Barbeque Chicken', 'Spicy Chicken', 'Chunky Chicken', 'Chicken Salami', 'Chicken Rashers'))], max_length=50, unique=True),
        ),
    ]
