# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0008_auto_20170126_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(choices=[('VEG', (('Black Olives', 'Black Olives'), ('Paneer', 'Paneer'), ('Mushroom', 'Mushroom'), ('Capsicum', 'Capsicum'), ('Golden Corn', 'Golden Corn'), ('Jalapeno', 'Jalapeno'), ('Fresh Tomato', 'Fresh Tomato'), ('Red Pepper', 'Red Pepper'), ('Red Paprika', 'Red Paprika'))), ('NON-VEG', (('Barbeque Chicken', 'Barbeque Chicken'), ('Spicy Chicken', 'Spicy Chicken'), ('Chunky Chicken', 'Chunky Chicken'), ('Chicken Salami', 'Chicken Salami'), ('Chicken Rashers', 'Chicken Rashers')))], max_length=50, unique=True),
        ),
    ]
