# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0009_auto_20170126_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='custom',
            field=models.BooleanField(default=True),
        ),
    ]
