# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0012_auto_20170223_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersite.Customer')),
                ('pizzas', models.ManyToManyField(blank=True, to='ordersite.Pizza')),
            ],
        ),
    ]
